name: Deploy Backend to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸쉬될 때 워크플로우가 실행됩니다.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@YOUR_EC2_IP << 'EOF'
          cd /var/www/backend
          git pull origin main
          ./gradlew build
          sudo systemctl restart your-backend-service
        EOF

